<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="picasa, image hosting, free photo sharing and video sharing. Upload your photos and share them with friends and family."/>
<meta name="keywords" content="picasa, album, free image hosting, image hosting, video hosting, photo image hosting site"/>
<title>Up Ảnh Free - NguyenPhongStudio.com</title>
<link id="page_favicon" href="favicon.ico" rel="icon" type="image/x-icon" />
<script type="text/javascript" src="script.js"></script> 
<link rel="stylesheet" href="style.css" type="text/css" />
</head>
<body>
<div id="wrapper">
	<div class="block">
    	<h1>UPLOAD ẢNH MIỄN PHÍ</h1>
        <div class="line">
            <a href="https://picasaweb.google.com/115872846525908427454/" target="_blank">Thư Viện Ảnh</a>
        </div>
         <div class="line">
			<div style="width: 750px; height: 40px; margin:0; padding: 0;">
            <h4>Upload ảnh từ:</h4><a href="?op=upload"><h2>Máy tính</h2></a> <a href="?op=transfer"><h2>URL</h2></a>
			</div>
        </div>
        <div class="line">
        	Đóng dấu ảnh: 
            <input type="radio" name="watermark" id="watermark" onclick="setWatermark(true);" checked="checked"/> Có
        	<input type="radio" name="watermark" onclick="setWatermark(false);"/> Không
        </div>		
		<? if(!$_GET['op'] || $_GET['op'] == 'upload'){?>      
            
			Nhấn Browser để chọn 1 file upload<br>            
			<input type="file" id="fileuploadpicasa" /> 	
			<input type="button" onclick="clearlist();transferlocal();" style="cursor:pointer;" value="Upload File" class="tranfer"/> 	
            
		<? }else{?>
			
            Nhập URL hình ảnh - Mỗi link trên một dòng<br />
            <textarea id="listurl" name="listurl" style="height:120px;width:100%" ></textarea>
            <input type="button" onclick="clearlist();transfer();" style="cursor:pointer;" value="Upload" class="tranfer"/> 	
        <? }?>
    </div>    
   	<div class="block">
        <div id="result"></div>
        <div id="loading"></div>
        <div id="getcode" style="display:none">
            <div>
                <a href="javascript:showcode('bbcode');">BBcode</a> | 
                <a href="javascript:showcode('html');">HTML</a> | Link trực tiếp: 
                <a href="javascript:showcode('none');">Fullsize</a> |  
				<a href="javascript:showcode('400');">400x</a>	| 
				<a href="javascript:showcode('640');">640x</a>	| 
				<a href="javascript:showcode('800');">800x</a>  |
				<a href="javascript:showcode('1024');">1024px</a> 
             </div>
            <div><textarea id="showcode" style="height:100px;width:100%" onclick="this.select();"></textarea></div>
        </div>
     </div>   
	<div class="block">
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script language="JavaScript" src="jquery.tinycarousel.min.js"></script>
			<div class="top_img" id="slider-code">
            	<h3>Ảnh mới nhất:</h3>
            	<a href="#" class="back prev"></a>
                <div class="slide viewport" id="slide">
					<ul class="overview">
<?php
	require("./config.php");
	require_once 'Zend/Loader.php';
	Zend_Loader::loadClass('Zend_Gdata');
	Zend_Loader::loadClass('Zend_Gdata_ClientLogin');
	Zend_Loader::loadClass('Zend_Gdata_Photos');
	Zend_Loader::loadClass('Zend_Http_Client');	
	
	$serviceName = Zend_Gdata_Photos::AUTH_SERVICE_NAME;
	$client = Zend_Gdata_ClientLogin::getHttpClient($user, $pass, $serviceName);

	// update the second argument to be CompanyName-ProductName-Version
	$gp = new Zend_Gdata_Photos($client, "Google-DevelopersGuide-1.0");
	$query = $gp->newUserQuery();

	// indicate the user's feed to retrieve
	$query->setUser("default");

	// set to only return photos
	// the default kind value for a user feed is to include only albums
	$query->setKind("photo");

	$query->setMaxResults($images_in_slide);

    // we're passing null for the username, as we want to send
    // additional query parameters generated by the UserQuery class
    $userFeed = $gp->getUserFeed(null, $query);

    // because we specified 'photo' for the kind, only PhotoEntry objects 
    // will be contained in the UserFeed
    foreach ($userFeed as $photoEntry) {
		if ($photoEntry->getMediaGroup()->getThumbnail() != null) {
		  $mediaThumbnailArray = $photoEntry->getMediaGroup()->getThumbnail();
		  $firstThumbnailUrl = $mediaThumbnailArray[1]->getUrl();
		}
		$link = $photoEntry->getLink('alternate')->getHref();
		$title = $photoEntry->getTitle()->getText();
        echo <<<abc
<li><a href="$link" title="$title">

						<table><tr><td style="height: 144px; width: 144px; vertical-align: bottom; text-align: center;">
							<img style="max-height: 144px; max-width: 144px" src="$firstThumbnailUrl" alt="$title" border="0" />
						 </td></tr></table>	
						</a>
						</li>		
abc;
    }
?>
</ul>
                </div>
            
            	<a href="#" class="next"></a>
            	<div class="clear"></div>
        	</div>

		<script language="JavaScript">
		$(document).ready(function() {
			$(".overview").find("img").error(function() {
				$(this).parentsUntil(".overview").remove();
			});
			if ( $(".overview").children().length == 0 )
				$('#slider-code').remove();
			$('#slider-code').tinycarousel({ display: 1, interval:true });
		});
		</script>
	</div>	 
</div><!--/#wrapper-->
<div align="center">© 2012 - <a href="http://nguyenphongstudio.com/picasa" title="Upload ảnh miễn phí" target="_blank">Nguyên Phong Studio</div>
</body>
</html>